spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true


#指定日志输出开始 由于logback-spring能够提升输出速度以及更加详细，故不用而注释掉这种输出
#logging:
#  pattern:
#    d指定日期 msg指定消息 n换行
#    console: "%d - %msg%n"
# 指定路径，path：不能指定文件名，文件名默认输出为spring.log ,但file：不仅可以指定文件路径，并且可以指定输出的文件名
#  path: D://
#  file: D://sell.log
#定义日志输出级别
#  level:
#    指定某一个类的日志级别
#    cn.xiaoshan.LoggerTest: debug
#指定日志输出结束