spring:
  profiles:
    active: dev
  #全局配置去除Json返回空数据
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
wechat:
  mpAppId: wxbbcc880c6c06faae
  mpAppSecret: 1a416d3061fdd48329b58eeb03fe38bc
  redirectUrl: www.xiaoshan2016.site/sell/wechat/authorize